# Generated by Django 5.2.3 on 2025-07-02 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_cart_cartitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
